imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: "%redis_dsn_default%"
            logging: '%kernel.debug%'
        cache:
            type: phpredis
            alias: cache
            dsn: "%redis_dsn_cache%"
            logging: false
        session:
            type: phpredis
            alias: session
            dsn: "%redis_dsn_session%"
            logging: false
        profiler_storage:
            type: phpredis
            alias: profiler_storage
            dsn: "%redis_dsn_profiler_storage%"
            logging: false
    session:
        client: session
        ttl: 31536000
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
        result_cache:
            client: cache
            entity_manager: [default]
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default
    monolog:
        client: cache
        key: monolog
    swiftmailer:
        client: default
        key: swiftmailer
    profiler_storage:
        client: profiler_storage
        ttl: 3600
